//JOB status
const CLIENT_REJECTED = 'CLIENT_REJECTED';
const CLEANER_PENDING = 'CLEANER_PENDING';
const CLEANER_APPROVED = 'CLEANER_APPROVED';
const CLEANER_REJECTED = 'CLEANER_REJECTED';

const PENDING = 'PENDING';
const CLEANER = 'CLEANER';
const CLIENT = "CLIENT";


module.exports = {
  CLIENT_REJECTED,
  CLEANER_PENDING,
  CLEANER_APPROVED,
  CLEANER_REJECTED,
  PENDING,
  CLEANER,
  CLIENT
}