cache:
  key:
  
stages:
  - build
  - test
  - deploy

after_script:
  - (if [ "$(lsof -n -i4TCP:2137)" != "" ]; then kill -9 $(lsof -n -i4TCP:2137); else echo "Cleaned"; exit 33; fi);


detox_test:iOS:
    stage: test
    before_script:
      - brew tap wix/brew
      - brew install --HEAD applesimutils
      - npm install -g detox-cli
      - npm install -g react-native-cli
      - npm install
    script:
        - react-native start --port 2137 &
        - detox build -c ios.sim.debug 
        - detox test -c ios.sim.debug
        - kill -9 $(lsof -n -i4TCP:2137) 
    tags:
        - xcode-9.2